@url = localhost:3001/api
@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMDk0YjdlYTUxMzUyM2IzNjJkMmZkMiIsImlhdCI6MTY2MTU1NzIyN30.rRDc-P4HPLUuFKiOIm4CIUe-9NESDN0rQB9N7bMBVm0

### Food Entries
GET http://{{url}}/foods HTTP/1.1
content-type: application/json

###
POST http://{{url}}/foods HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "calorie": 300
}

###
POST http://{{url}}/foods HTTP/1.1
content-type: application/json
Authorization: {{authorization}}

{
    "name": "sample",
    "calorie": 1000,
    "price": 10
}

### Users
GET http://{{url}}/users/ HTTP/1.1
content-type: application/json

###
POST http://{{url}}/users HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "yinyin",
    "password": "password"
}

###
POST http://{{url}}/login HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "password"
}